version: '3.5'

services:

  trader-db:
    container_name: trader-db
    image: mariadb:10.3
    restart: always
    env_file:
      - .env.test
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  flask-middleware:
    container_name: trader-backend
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    env_file:
      - .env.test
    volumes:
      - "./backend:/app"
    depends_on:
      - "trader-db"

  react-client:
    container_name: trader-client
    build:
      context: ./client/
      dockerfile: Dockerfile
    working_dir: '/app'
    volumes:
      - './client:/app'
      - '/app/node_modules'
    ports:
      - '3000:3000'
    depends_on:
      - "flask-middleware"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
